<?php
declare(strict_types=1);
/* $task = $this->task ?? [];
$action = $action ??'';
$readonly = true;
$buttonText = 'Actualizar';
$updateUrl = Environment::url('task/update') . '?id=' . htmlspecialchars((string)$task['id']);
$showDelete = false;
$cancelUrl = '';

include dirname(__DIR__, 2) . '/layouts/form.phtml'; */

$task = $this->task ?? [];
$action = $action ??'';
$readonly = false;
$buttonText = '';
$updateUrl = Environment::url('task/update') . '?id=' . htmlspecialchars((string)($task['id'] ?? ''));
$showDelete = true;
$cancelUrl = Environment::url('/');

include dirname(__DIR__, 2) . '/layouts/form.phtml';
?>